### ISSUE TITLE
Contributor Signup

### ISSUE THREAD

**Issue by cmgriffing** [cmgriffing/xyz-firewall#1]
If you would like to help contribute to this project, please comment on this issue so that I can tag you in the future on other issues and PRs.

**Comment by Kameth11** [comment]
i would like to help !

**Comment by Sglavin85** [comment]
I'd like to help with this

**Comment by cmgriffing** [comment]
The first simple step would be to add the Fonts via this issue: https://github.com/cmgriffing/xyz-firewall/issues/2

Go ahead and comment on that Issue if it something you want to take on.

**Comment by cmgriffing** [comment]
Closing all issues as this project is now Archived.
