### ISSUE TITLE
Add Fonts

### ISSUE THREAD

**Issue by cmgriffing** [cmgriffing/xyz-firewall#2]
We need to add the fonts to the site.

Using Helmet and adding the `<link>` element in the layout.js file would make the most sense for now.

We can use all font weights and styles for now and optimize later.

Body Text: Archivo Narrow
https://fonts.google.com/specimen/Archivo+Narrow

Title/Logo Font: Archivo Black
https://fonts.google.com/specimen/Archivo+Black

**Comment by ulricksennick** [comment]
Borang here!

**Comment by borang-dev** [comment]
Borang here.  Would you mind reassigning?
